name: phd_idi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - numpy
  - scipy
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - duckdb
  - pyarrow
  - openpyxl
  - pytest
  - pyyaml
  - pip
  - pip:
      - linearmodels
      - lifelines
